name: Bug Report
description: Report a bug in @rn-ui components or core
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Render <Button variant="outlined">...</Button>
        2. Press the button
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include screenshots or logs if applicable.
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - "@rn-ui/core"
        - "@rn-ui/components"
        - Both
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - iOS
        - Android
        - Web
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: "0.1.0"

  - type: input
    id: rn-version
    attributes:
      label: React Native version
      placeholder: "0.81.5"

  - type: input
    id: expo-version
    attributes:
      label: Expo SDK version
      placeholder: "54"
