name: Feature Request
description: Suggest a new component, feature, or improvement
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature or improvement you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed API
      description: If applicable, show how the API or usage would look.
      placeholder: |
        <Chip variant="filter" selected onPress={handlePress}>
          Filter label
        </Chip>

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - "@rn-ui/core"
        - "@rn-ui/components"
        - New package
    validations:
      required: true
